function generate_wedge_hull()
%GENERATE_WEDGE_HULL Create a watertight wedge-prism benchmark mesh.
% Coordinate system: Z=0 at keel, Z=D at deck.
%
% Cross-section (YZ plane) is triangular:
%   keel: (y=0, z=0)
%   deck edges: (y=+/-B/2, z=D)
% Extruded uniformly along x over length L.

    L = 8.0;
    B = 3.0;
    D = 2.0;

    fprintf('Generating Wedge hull...\n');
    fprintf('  L = %.2f m, B = %.2f m, D = %.2f m\n', L, B, D);
    fprintf('  Coordinate system: Z=0 at keel, Z=D at deck\n');

    x0 = -L/2;
    x1 =  L/2;

    % Stern section (x0)
    ks = [x0, 0,    0   ];   % keel
    ps = [x0, B/2,  D   ];   % port deck edge
    ss = [x0, -B/2, D   ];   % starboard deck edge

    % Bow section (x1)
    kb = [x1, 0,    0   ];
    pb = [x1, B/2,  D   ];
    sb = [x1, -B/2, D   ];

    vertices = [ks; ps; ss; kb; pb; sb];

    % Faces with outward winding
    faces = [
        % Stern triangular cap (normal -x)
        1, 3, 2;
        % Bow triangular cap (normal +x)
        4, 5, 6;

        % Port sloped face
        1, 2, 5;
        1, 5, 4;

        % Starboard sloped face
        1, 4, 6;
        1, 6, 3;

        % Deck face (z = D)
        2, 3, 6;
        2, 6, 5;
    ];

    fprintf('  Generated %d vertices, %d faces\n', size(vertices, 1), size(faces, 1));

    check_mesh(vertices, faces, L, B, D);

    output_file = fullfile(fileparts(mfilename('fullpath')), 'Wedge_hull_mesh.obj');
    write_obj_file(output_file, vertices, faces, L, B, D);
    fprintf('  Saved: %s\n', output_file);

    fprintf('\n  Theoretical properties:\n');
    for T = [0.5, 1.0, 1.5]
        A = B * T^2 / (2*D);
        V = L * A;
        KB = (2/3) * T;
        Af = L * B * (T/D);
        fprintf('    T=%.1f m: V=%.4f m^3, KB=%.4f m, Af=%.4f m^2\n', T, V, KB, Af);
    end
end

function check_mesh(vertices, faces, L, B, D)
    edges = [faces(:,[1 2]); faces(:,[2 3]); faces(:,[3 1])];
    edgesSorted = sort(edges, 2);
    [~, ~, edgeIds] = unique(edgesSorted, 'rows');
    edgeCount = accumarray(edgeIds, 1);
    nBoundary = nnz(edgeCount == 1);
    nNonManifold = nnz(edgeCount > 2);

    fprintf('  Mesh check: %d boundary edges, %d non-manifold edges\n', nBoundary, nNonManifold);
    if nBoundary == 0
        fprintf('  Mesh is watertight.\n');
    else
        fprintf('  Warning: Mesh is not watertight!\n');
    end

    vol = compute_volume(vertices, faces);
    expected_vol = L * B * D / 2;
    fprintf('  Mesh volume: %.4f m^3 (expected: %.4f m^3, error: %.2f%%)\n', ...
        vol, expected_vol, abs(vol-expected_vol)/expected_vol*100);
end

function vol = compute_volume(vertices, faces)
    v1 = vertices(faces(:,1), :);
    v2 = vertices(faces(:,2), :);
    v3 = vertices(faces(:,3), :);
    vol = sum(dot(v1, cross(v2, v3, 2), 2)) / 6;
    vol = abs(vol);
end

function write_obj_file(filename, vertices, faces, L, B, D)
    fid = fopen(filename, 'w');
    if fid < 0
        error('Cannot open file: %s', filename);
    end

    fprintf(fid, '# Wedge Hull Mesh\n');
    fprintf(fid, '# Generated by NAUTILUS\n');
    fprintf(fid, '# L=%.2f, B=%.2f, D=%.2f\n', L, B, D);
    fprintf(fid, '# Coordinate system: Z=0 at keel, Z=D at deck\n');
    fprintf(fid, '#\n');

    for i = 1:size(vertices, 1)
        fprintf(fid, 'v %.10f %.10f %.10f\n', vertices(i,1), vertices(i,2), vertices(i,3));
    end

    for i = 1:size(faces, 1)
        fprintf(fid, 'f %d %d %d\n', faces(i,1), faces(i,2), faces(i,3));
    end

    fclose(fid);
end
