function generate_box_barge()
%GENERATE_BOX_BARGE Creates a proper watertight box barge mesh
% Coordinate system: Z=0 at KEEL, Z=D at deck (matching original code expectation)
% This ensures proper hydrostatics calculation

    L = 10.0;       % Length [m]
    B = 4.0;        % Beam [m]
    D = 2.0;        % Depth [m]

    fprintf('Generating Box Barge hull...\n');
    fprintf('  L = %.2f m, B = %.2f m, D = %.2f m\n', L, B, D);
    fprintf('  Coordinate system: Z=0 at KEEL, Z=D at deck\n');

    % Define 8 corners of the box
    % x: -L/2 to L/2
    % y: -B/2 to B/2
    % z: 0 to D (keel to deck)

    corners = [
        -L/2, -B/2, 0;   % 1: stern, port, keel
         L/2, -B/2, 0;   % 2: bow, port, keel
         L/2,  B/2, 0;   % 3: bow, starboard, keel
        -L/2,  B/2, 0;   % 4: stern, starboard, keel
        -L/2, -B/2, D;   % 5: stern, port, deck
         L/2, -B/2, D;   % 6: bow, port, deck
         L/2,  B/2, D;   % 7: bow, starboard, deck
        -L/2,  B/2, D;   % 8: stern, starboard, deck
    ];

    % Define 12 faces (2 triangles per rectangular face)
    % Note: winding order for outward normals
    faces = [
        % Bottom face (keel, z = 0) - normal points down (-z)
        1, 2, 3;
        1, 3, 4;

        % Top face (deck, z = D) - normal points up (+z)
        5, 7, 6;
        5, 8, 7;

        % Port side (y = -B/2) - normal points to port (-y)
        1, 6, 2;
        1, 5, 6;

        % Starboard side (y = B/2) - normal points to starboard (+y)
        4, 3, 7;
        4, 7, 8;

        % Stern (x = -L/2) - normal points to stern (-x)
        1, 4, 8;
        1, 8, 5;

        % Bow (x = L/2) - normal points to bow (+x)
        2, 6, 7;
        2, 7, 3;
    ];

    vertices = corners;

    fprintf('  Generated %d vertices, %d faces\n', size(vertices, 1), size(faces, 1));

    % Verify mesh
    check_mesh(vertices, faces, L, B, D);

    % Write OBJ file
    output_file = fullfile(fileparts(mfilename('fullpath')), 'BoxBarge_mesh.obj');
    write_obj_file(output_file, vertices, faces, L, B, D);
    fprintf('  Saved: %s\n', output_file);

    % Print theoretical properties
    fprintf('\n  Theoretical properties:\n');
    for T = [0.5, 1.0, 1.5]
        V = L * B * T;
        KB = T / 2;
        fprintf('    T=%.1f m: V=%.1f m³, KB=%.2f m\n', T, V, KB);
    end
end

function check_mesh(vertices, faces, L, B, D)
    % Check for boundary edges
    edges = [faces(:,[1 2]); faces(:,[2 3]); faces(:,[3 1])];
    edgesSorted = sort(edges, 2);
    [~, ~, edgeIds] = unique(edgesSorted, 'rows');
    edgeCount = accumarray(edgeIds, 1);
    nBoundary = nnz(edgeCount == 1);
    nNonManifold = nnz(edgeCount > 2);

    fprintf('  Mesh check: %d boundary edges, %d non-manifold edges\n', nBoundary, nNonManifold);

    if nBoundary > 0
        fprintf('  Warning: Mesh is not watertight!\n');
    else
        fprintf('  Mesh is watertight.\n');
    end

    % Check volume
    vol = compute_volume(vertices, faces);
    expected_vol = L * B * D;
    fprintf('  Mesh volume: %.2f m^3 (expected: %.2f m^3, error: %.1f%%)\n', ...
        vol, expected_vol, abs(vol-expected_vol)/expected_vol*100);
end

function vol = compute_volume(vertices, faces)
    v1 = vertices(faces(:,1), :);
    v2 = vertices(faces(:,2), :);
    v3 = vertices(faces(:,3), :);
    vol = sum(dot(v1, cross(v2, v3, 2), 2)) / 6;
    vol = abs(vol);
end

function write_obj_file(filename, vertices, faces, L, B, D)
    fid = fopen(filename, 'w');
    if fid < 0
        error('Cannot open file: %s', filename);
    end

    fprintf(fid, '# Box Barge Mesh\n');
    fprintf(fid, '# Generated by NAUTILUS\n');
    fprintf(fid, '# L=%.2f, B=%.2f, D=%.2f\n', L, B, D);
    fprintf(fid, '# Coordinate system: Z=0 at KEEL, Z=D at deck\n');
    fprintf(fid, '#\n');

    for i = 1:size(vertices, 1)
        fprintf(fid, 'v %.6f %.6f %.6f\n', vertices(i, 1), vertices(i, 2), vertices(i, 3));
    end

    for i = 1:size(faces, 1)
        fprintf(fid, 'f %d %d %d\n', faces(i, 1), faces(i, 2), faces(i, 3));
    end

    fclose(fid);
end
